name: Build

on:
  push:
    branches:
      - feature/github-action
    paths-ignore:
      - '**.md'
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.yaml'
      - '**.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      GO_VERSION: 1.16
      CGO_ENABLED: 0
      PRE_TARGET: ""

    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]

    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/traefik/traefik

    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: go/src/github.com/traefik/traefik
          fetch-depth: 0

      # https://github.com/marketplace/actions/cache
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
            ~/Library/Caches/go-build # Build cache (Mac)
            '%LocalAppData%\go-build' # Build cache (Windows)
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Installing dependencies
        run: |
          go install github.com/containous/go-bindata/go-bindata@v1.0.0

      - name: Build
        run: |
          make binary
