name: Build

on:
  push:
    branches:
      - feature/github-action
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      GO_VERSION: 1.16
      CGO_ENABLED: 0
      PRE_TARGET: ""

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        arch: [ amd64 ]

    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/traefik/traefik

    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Installing dependencies
        run: |
          go version
          go env
          go install -v github.com/containous/go-bindata/go-bindata@v1.0.0

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build on ${{ matrix.os }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          make binary
