name: Build

on:
  push:
    branches:
      - feature/github-action
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      PRE_TARGET: ""
      CGO_ENABLED: 0
      GOGC: off
    strategy:
      matrix:
        os: [ linux, darwin, windows ]
        arch: [ amd64 ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Installing dependancies
        run: |
          go get -u github.com/containous/go-bindata/...
          go get k8s.io/gengo/...

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: go/src/github.com/traefik/traefik

      - name: Generate
        working-directory: go/src/github.com/traefik/traefik
        run: |
          ./script/make.sh generate

      - name: Build
        working-directory: go/src/github.com/traefik/traefik
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          ./script/make.sh binary
